#ifndef WORLDCONSTANTS_H_INCLUDED
#define WORLDCONSTANTS_H_INCLUDED

constexpr int   CHUNK_SIZE      = 16,
				CHUNK_HEIGHT	= 256,
                CHUNK_AREA      = CHUNK_SIZE * CHUNK_SIZE,
                CHUNK_VOLUME    = CHUNK_SIZE * CHUNK_SIZE * CHUNK_HEIGHT,

                WATER_LEVEL     = 64;

#endif // WORLDCONSTANTS_H_INCLUDED
